set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(ImgWindowExample)
target_sources(ImgWindowExample PRIVATE ImgWindowExample.cpp)
target_link_libraries(ImgWindowExample PRIVATE WinIMerge)

add_executable(ImgMergeBufferExample)
target_sources(ImgMergeBufferExample PRIVATE ImgMergeBufferExample.cpp)
target_link_libraries(ImgMergeBufferExample PRIVATE WinIMerge)
