# SPDX-FileCopyrightText: Copyright © 2023 Dominik Wójt <domin144@o2.pl>
#
# SPDX-License-Identifier: GPL-2.0-or-later

version_header = vcs_tag(input : 'gen-versioninfo.h.in', output : 'gen-versioninfo.h')
version_header_inc = meson.current_build_dir()

subdir('WinIMergeLib')
subdir('WinIMerge')
subdir('cidiff')
